AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  payments-processor
  
  Demonstration of AWS SAM application

Parameters:
  RecieptsBucketName:
    Type: String
    Default: payments-receipts
    Description: The name of S3 bucket where all the receipts are stored
  PaymentsQueueName:
    Type: String
    Default: paymentsQueue.fifo
    Description: Name of the payments queue
  
Globals:
  Function:
    Timeout: 10
    Handler: app.lambdaHandler
    Runtime: nodejs12.x
    

Resources:
#Functions 
#----------------------------------------

  ReceiptExtractorStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: app-receipts-extractor
      DefinitionUri: state-machines/receipts-extractor.asl.json
      Events:
        CloudTrailEvent:
          Type: EventBridgeRule
          Properties:
            
      DefinitionSubstitutions:
        ReceiptsReadeArn: !GetAtt ReceiptReaderFunction.Arn
        PaymentsProcessorArn: !GetAtt PaymentsProcessorFunction.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref ReceiptReaderFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref PaymentsProcessorFunction

  ReceiptReaderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: app-receipt-reader
      CodeUri: receipts-reader/
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref RecieptsBucketName
  
  PaymentsProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: app-payments-processor
      CodeUri: payments-processor/
      Environment:
        Variables:
          QueueUrl: !Ref PaymentsQueue
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !Ref PaymentsQueueName

#-----------------------------------------

#Services
#-----------------------------------------

  ReceiptsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref RecieptsBucketName
  PaymentsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref PaymentsQueueName
      FifoQueue: true
      ContentBasedDeduplication: true

#----------------------------------------

#Permissions and roles
#----------------------------------------

  # S3TriggerReceiptExtractorPermission:
  #   Type: AWS::Lambda::Permission
  #   Properties:
  #     Action: 'lambda:InvokeFunction'
  #     FunctionName: !Ref ReceiptExtractorFunction
  #     Principal: s3.amazonaws.com
  #     SourceArn: !GetAtt ReceiptsBucket.Arn

#----------------------------------------

      
Outputs:
  ReceiptsBucket:
    Description: "Created Receipts Bucket Arn"
    Value: !GetAtt ReceiptsBucket.Arn
  PaymentsQueue:
    Description: "Payments Queue URL"
    Value: !Ref PaymentsQueue

