AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  payments-processor
  
  Demonstration of AWS SAM application

Parameters:
  RecieptsBucketName:
    Type: String
    Default: payments-receipts
    Description: The name of S3 bucket where all the receipts are stored
  PaymentsQueueName:
    Type: String
    Default: paymentsQueue.fifo
    Description: Name of the payments queue
  CloudTrailBucketName:
    Type: String
    Default: payments-receipts-cloudtrail-event-bucket
    Description: Name of the cloud trail log buckets
  ErrorEmailAddress:
    Type: String
    Default: samjerusalem@gmail.com
    Description: Email address for notifying function errors
  PaymentsTableName:
    Type: String
    Default: payments
    Description: Database where payments are persisted

  
Globals:
  Function:
    Timeout: 10
    Handler: app.lambdaHandler
    Runtime: nodejs12.x
    

Resources:
#Functions 
#----------------------------------------
  
  ReceiptReaderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: app-receipt-reader
      CodeUri: functions/receipts-reader/
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref RecieptsBucketName
  PaymentsProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: app-payments-processor
      CodeUri: functions/payments-processor/
      Environment:
        Variables:
          QueueUrl: !Ref PaymentsQueue
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !Ref PaymentsQueueName
  PaymentsPersistorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: app-payments-persistor
      CodeUri: functions/payments-persistor/
      Events:
        PaymentsQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt PaymentsQueue.Arn
            BatchSize: 10
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref PaymentsDB
      Environment:
        Variables:
          TABLE_NAME: !Ref PaymentsTableName
  PaymentsNotifierFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: app-payments-notifier
      CodeUri: functions/payments-notifier/
      Layers:
        - !Ref UtilsLayer
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt PaymentsDB.StreamArn
            BatchSize: 100
            StartingPosition: TRIM_HORIZON
  PaymentsRetrieverFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: app-payments-retriever
      CodeUri: functions/payment-retriever/
      Layers:
        - !Ref UtilsLayer
      Policies:
        DynamoDBReadPolicy:
          TableName: !Ref PaymentsDB
      Environment:
        Variables:
          TABLE_NAME: !Ref PaymentsTableName
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: '/payments'
            Method: get

#Layers 
#----------------------------------------

  UtilsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: Utils
      Description: Utilities and other helper functions
      ContentUri: layers/utils/
      CompatibleRuntimes:
        - nodejs12.x
        - nodejs8.10
      RetentionPolicy: Retain

#-----------------------------------------

#Services
#-----------------------------------------
  ReceiptExtractorStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: app-receipts-extractor
      DefinitionUri: state-machines/receipts-extractor.asl.json
      Events:
        S3PutEvent:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - "aws.s3"
              detail:
                requestParameters:
                  bucketName:
                    - !Ref RecieptsBucketName
                eventSource:
                  - s3.amazonaws.com
                eventName:
                  - PutObject
      DefinitionSubstitutions:
        ReceiptsReadeArn: !GetAtt ReceiptReaderFunction.Arn
        PaymentsProcessorArn: !GetAtt PaymentsProcessorFunction.Arn
        ErrorTopicArn: !Ref AppErrorSnsTopic
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref ReceiptReaderFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref PaymentsProcessorFunction
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt AppErrorSnsTopic.TopicName
  ReceiptsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref RecieptsBucketName
  CloudTrailBucket: 
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref CloudTrailBucketName
  PaymentsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref PaymentsQueueName
      FifoQueue: true
      ContentBasedDeduplication: true
  AppErrorSnsTopic:
    Type: AWS::SNS::Topic
    Properties: 
      FifoTopic: false
      Subscription: 
        - Endpoint: !Ref ErrorEmailAddress
          Protocol: email-json
      TopicName: AppErrorNotifier
  S3EventCloudTrail: 
    Type: AWS::CloudTrail::Trail
    DependsOn: 
      - CloudTrailBucketPolicy
    Properties: 
      TrailName: S3EventCloudTrail
      S3BucketName: !Ref CloudTrailBucketName
      IsLogging: true
      IsMultiRegionTrail: false
      EventSelectors:
        - IncludeManagementEvents: false
          DataResources:
            - Type: AWS::S3::Object
              Values: 
                - !Sub arn:aws:s3:::${RecieptsBucketName}/
      IncludeGlobalServiceEvents: false
  PaymentsDB:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions:
        - 
          AttributeName: "id"
          AttributeType: "S"
        -
          AttributeName: "date"
          AttributeType: "S"
      KeySchema:
        - 
          AttributeName: "id"
          KeyType: "HASH"
        -
          AttributeName: "date"
          KeyType: "RANGE"   
      BillingMode: PROVISIONED
      ProvisionedThroughput: 
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      TableName: !Ref PaymentsTableName
      StreamSpecification:
        StreamViewType: NEW_IMAGE
          
#----------------------------------------

# Permissions, roles and policies
#----------------------------------------
  # S3TriggerReceiptExtractorPermission:
  #   Type: AWS::Lambda::Permission
  #   Properties:
  #     Action: 'lambda:InvokeFunction'
  #     FunctionName: !Ref ReceiptExtractorFunction
  #     Principal: s3.amazonaws.com
  #     SourceArn: !GetAtt ReceiptsBucket.Arn

  CloudTrailBucketPolicy: 
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref CloudTrailBucket
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Sid: "AWSCloudTrailAclCheck"
            Effect: "Allow"
            Principal: 
              Service: "cloudtrail.amazonaws.com"
            Action: "s3:GetBucketAcl"
            Resource: !Sub arn:aws:s3:::${CloudTrailBucketName}
          - 
            Sid: "AWSCloudTrailWrite"
            Effect: "Allow"
            Principal: 
              Service: "cloudtrail.amazonaws.com"
            Action: "s3:PutObject"
            Resource: !Sub arn:aws:s3:::${CloudTrailBucketName}/AWSLogs/${AWS::AccountId}/*
            Condition: 
              StringEquals:
                s3:x-amz-acl: "bucket-owner-full-control"

#----------------------------------------

      
Outputs:
  ReceiptsBucket:
    Description: "Created Receipts Bucket Arn"
    Value: !GetAtt ReceiptsBucket.Arn
  PaymentsQueue:
    Description: "Payments Queue URL"
    Value: !Ref PaymentsQueue
  PaymentsDB:
    Description: "Payments Database Arn"
    Value: !GetAtt PaymentsDB.Arn